version: "3.4"

services:
  app:
    image: pos/node:v1
    volumes: 
      - ./:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
  
  db:
    image: mongo:latest
    volumes: 
      - .docker/data/db:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

