version: "3.4"

services:
  app:
    image: pos/node:v1
    volumes: 
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
       - db
    restart: unless-stopped



  db:
    image: mongo:latest
    volumes: 
      - .docker/data/db:/data/db
    restart: unless-stopped
